#!/bin/sh
#release=natty
#architecure=i386
username=ubuntu
archive_areas="main universe restricted"
archive="http://archive.ubuntu.com/ubuntu"
security="http://security.ubuntu.com/ubuntu"
#description="Standard Ubuntu Server with cloud init"
#name="Ubuntu Natty 11.04 Server"
#other_sources="ppa-brightbox-build ppa-brightbox-experimental"
#package_list="brightbox-ubuntu-${release}-server"
#compatibility=0
lb config noauto \
	-d ${release} --parent-distribution ${release} \
	-a "${architecture}" \
	--package-lists "${package_list}" \
	--security true --source true --source-images none --backports false  \
	--volatile true --apt-indices none --clean \
	--binary-images hdd --binary-filesystem ext4 \
        --hdd-size 20% --hdd-label "ubuntu-rootfs" \
	--chroot-filesystem none --archive-areas "${archive_areas}" \
	--parent-archive-areas "${archive_areas}" \
	--bootstrap-flavour standard \
	--parent-mirror-bootstrap "${archive}" \
	--parent-mirror-chroot "${archive}" \
	--parent-mirror-chroot-security "${security}" \
	--parent-mirror-chroot-volatile "${archive}" \
	--parent-mirror-chroot-backports none \
	--parent-mirror-binary "${archive}" \
	--parent-mirror-binary-backports none \
	--parent-mirror-binary-security "${security}" \
	--parent-mirror-binary-volatile "${archive}" \
	--mirror-binary "${archive}" \
	--mirror-binary-security "${security}" \
	--mirror-binary-volatile "${archive}" \
	--mirror-binary-backports none \
	--mirror-bootstrap "${archive}" \
	--mirror-debian-installer "${archive}" \
	--mirror-chroot-security "${archive}" \
	--mirror-chroot-volatile "${archive}" \
	--mirror-chroot-backports none \
	--net-tarball false --username "${username}" --exposed-root false \
	--keyring-packages ubuntu-keyring --linux-flavours virtual \
	--linux-packages '' \
	--initsystem none --initramfs none --mode ubuntu --tasksel tasksel \
	--bootloader grub2 --debian-installer-gui false \
        --debian-installer false \
	--debian-installer-distribution '' \
	--iso-application none --iso-preparer "${compatibility}" \
	--iso-publisher "${description}" \
	--iso-volume "${name}" --memtest none \
	--net-root-filesystem none --net-root-path '/srv/ubuntu-live' \
	--apt-options "--yes --force-yes -o Acquire::http::No-Cache=True -o Acquire::Retries=3 -o APT::Get::AllowUnauthenticated=true" \
	--root-command sudo \
	--gzip-options "--fast --rsyncable" \
        --archives "${other_sources}"
#Exclude archive directories from binary
mkdir -p config/binary_rootfs
> config/binary_rootfs/excludes
for word in ${other_sources}
do
  cat >> config/binary_rootfs/excludes <<EOF
/etc/apt/sources.list.d/${word}.list
/etc/apt/sources.list.d/${word}.key
EOF
done
#Reconfigure console
mkdir -p config/hooks
cat >config/hooks/reconfigure-console.chroot <<EOF
#!/bin/sh

set -e

export OVERRIDE_ALLOW_PRESEEDING=1

if apt-cache show keyboard-configuration >/dev/null 2>&1
then
    dpkg-reconfigure --frontend=noninteractive -u keyboard-configuration
fi
dpkg-reconfigure --frontend=noninteractive -u console-setup
EOF
